package game.scene.worldscene.subui

import indigo.*
import game.generated.Assets
import game.common.constant.Layout.tileSize
import game.common.Types.*
import game.common.util.TileMap.*

object TerrainUI:

  /** Terrain is drawn with `CloneTiles` (hardware instancing) from `assets/tiles.png`, which is
    * generated by `game/tools/gen_tileset.py`. Tile indices below must match that script's order.
    *
    * Drawing each tile as ordinary primitives costs one pipeline pass per node; a map screen needs
    * ~2000 of them, which caps the frame rate far below 60 FPS.
    *
    * Draws the whole map: the static tiles (cached by the renderer) plus the animated water.
    */
  def terrainUI(map: TileMap, time: Seconds): Batch[SceneNode] =
    Batch(staticTilesUI(map), waterTilesUI(map, time))

  private val cloneId: CloneId = CloneId("terrain")

  /** Must be added to the scene (`addCloneBlanks`) for `terrainUI` to draw. */
  val terrainCloneBlankUI: CloneBlank =
    CloneBlank(cloneId, Graphic(tileSize, tileSize, Material.Bitmap(Assets.assets.tiles)))

  private val waterFrames: Int = 4

  private def speck(cell: Point): Int =
    (cell.x * 7 + cell.y * 13) % 5

  /** Index of the tile image for a static (non-animated) tile. */
  private def staticIndex(tile: Tile, cell: Point): Int =
    tile match
      case Tile.Grass   => if speck(cell) == 0 then 1 else 0
      case Tile.Flowers => 2
      case Tile.Path    => if speck(cell) < 2 then 4 else 3
      case Tile.Floor   => 5
      case Tile.Water   => 6
      case Tile.Tree    => 14
      case Tile.Rock    => 15
      case Tile.Wall    => 16
      case Tile.Roof    => 17

  private def waterIndex(cell: Point, time: Seconds): Int =
    val variant = Math.floorMod(cell.x, 2)
    val frame   = (((time.toDouble * 8).toInt + cell.x * 5 + cell.y * 3) % 12) / 3
    6 + variant * waterFrames + frame

  private def tileData(cell: Point, index: Int): CloneTileData =
    CloneTileData(cell.x * tileSize, cell.y * tileSize, index * tileSize, 0, tileSize, tileSize)

  private def cells(map: TileMap): Batch[Point] =
    Batch.fromIndexedSeq(
      for {
        y <- 0 until map.size.height
        x <- 0 until map.size.width
      } yield Point(x, y)
    )

  /** Everything except water never changes, so the renderer caches it under a static key. */
  private def staticTilesUI(map: TileMap): CloneTiles =
    CloneTiles(
      cloneId,
      cells(map)
        .filter(c => tileAt(c)(map) != Tile.Water)
        .map(c => tileData(c, staticIndex(tileAt(c)(map), c)))
    ).withStaticBatchKey(BindingKey("static-terrain"))

  private def waterTilesUI(map: TileMap, time: Seconds): CloneTiles =
    CloneTiles(
      cloneId,
      cells(map)
        .filter(c => tileAt(c)(map) == Tile.Water)
        .map(c => tileData(c, waterIndex(c, time)))
    )
