package rpg.common.asset

import indigo.*
import rpg.generated.Assets

/** Sound effects, as ready-to-send effects (`PlaySound` events). The clips are generated by
  * `rpg/tools/gen_sfx.py`.
  */
object Sfx:

  private val volume: Volume = Volume(0.5)

  val title: PlaySound   = PlaySound(Assets.assets.sfxTitle, volume)
  val world: PlaySound   = PlaySound(Assets.assets.sfxWorld, volume)
  val battle: PlaySound  = PlaySound(Assets.assets.sfxBattle, volume)
  val victory: PlaySound = PlaySound(Assets.assets.sfxVictory, volume)
  val defeat: PlaySound  = PlaySound(Assets.assets.sfxDefeat, volume)
